package com.cajsa.moodleaf.ui.editor

import android.content.Context
import android.net.Uri
import androidx.compose.ui.geometry.Offset
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.cajsa.moodleaf.data.datastore.UserPreferencesRepository
import com.cajsa.moodleaf.data.repository.JournalRepository
import com.cajsa.moodleaf.data.repository.PageElementRepository
import com.cajsa.moodleaf.data.repository.WeatherRepository
import com.cajsa.moodleaf.model.ElementType
import com.cajsa.moodleaf.model.JournalEntry
import com.cajsa.moodleaf.model.Mood
import com.cajsa.moodleaf.model.NoteShape
import com.cajsa.moodleaf.model.PageElement
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.time.Instant
import java.time.LocalDate
import java.time.LocalTime
import java.time.ZoneId
import java.util.UUID
import javax.inject.Inject

data class EditorUiState(
    val entryId: Long? = null,
    val mood: Mood = Mood.OKAY,
    val createdAt: Instant = Instant.now(),
    val elements: List<PageElement> = emptyList(),
    val weatherCode: Int? = null,
    val tempC: Double? = null,
    val isSaved: Boolean = false
)

@HiltViewModel
class EditorViewModel @Inject constructor(
    private val journalRepository: JournalRepository,
    private val pageElementRepository: PageElementRepository,
    private val weatherRepository: WeatherRepository,
    private val userPreferencesRepository: UserPreferencesRepository,
    @param:ApplicationContext private val context: Context,
    savedStateHandle: SavedStateHandle
) : ViewModel() {

    private val _uiState = MutableStateFlow(EditorUiState())
    val uiState: StateFlow<EditorUiState> = _uiState.asStateFlow()

    // Unsaved elements need a distinct in-memory identity before they have a real,
    // positive Room id — negative ids never collide with an autogenerated one.
    private var localIdCounter = 0L
    private fun nextLocalId(): Long = --localIdCounter

    init {
        val entryId: Long? = savedStateHandle.get<Long>("entryId")?.takeIf { it != -1L }
        if (entryId != null) {
            viewModelScope.launch {
                journalRepository.getEntry(entryId)?.let { entry ->
                    _uiState.update {
                        it.copy(
                            entryId = entry.id,
                            mood = entry.mood,
                            createdAt = entry.createdAt,
                            weatherCode = entry.weatherCode,
                            tempC = entry.tempC
                        )
                    }
                }
                val elements = pageElementRepository.observeElements(entryId).first()
                _uiState.update { it.copy(elements = elements) }
            }
        } else {
            val epochDay: Long? = savedStateHandle.get<Long>("date")?.takeIf { it != -1L }
            val createdAt = if (epochDay != null) {
                LocalDate.ofEpochDay(epochDay).atTime(LocalTime.NOON).atZone(ZoneId.systemDefault()).toInstant()
            } else {
                Instant.now()
            }
            _uiState.update {
                it.copy(createdAt = createdAt, elements = listOf(defaultNoteElement()))
            }
            fetchWeather()
        }
    }

    fun fetchWeather() {
        viewModelScope.launch {
            val city = userPreferencesRepository.preferences.first().weatherCity
            if (city.isBlank()) return@launch
            val reading = weatherRepository.fetchWeatherForCity(city) ?: return@launch
            _uiState.update { it.copy(weatherCode = reading.weatherCode, tempC = reading.tempC) }
        }
    }

    private fun defaultNoteElement() = PageElement(
        id = nextLocalId(),
        entryId = 0,
        type = ElementType.NOTE,
        content = "",
        x = 0.5f,
        y = 0.7f
    )

    private fun nextZIndex(elements: List<PageElement>): Int =
        (elements.maxOfOrNull { it.zIndex } ?: -1) + 1

    fun onMoodSelected(mood: Mood) {
        _uiState.update { it.copy(mood = mood) }
    }

    fun onDateTimeChanged(dateTime: Instant) {
        _uiState.update { it.copy(createdAt = dateTime) }
    }

    fun addPhotoElement(uri: Uri) {
        viewModelScope.launch {
            val copiedPath = withContext(Dispatchers.IO) {
                val imagesDir = File(context.filesDir, "journal_images").apply { mkdirs() }
                val destination = File(imagesDir, "${UUID.randomUUID()}.jpg")
                context.contentResolver.openInputStream(uri)?.use { input ->
                    destination.outputStream().use { output -> input.copyTo(output) }
                }
                destination.absolutePath
            }
            _uiState.update { state ->
                val element = PageElement(
                    id = nextLocalId(),
                    entryId = state.entryId ?: 0,
                    type = ElementType.PHOTO,
                    content = copiedPath,
                    x = 0.5f,
                    y = 0.35f,
                    zIndex = nextZIndex(state.elements)
                )
                state.copy(elements = state.elements + element)
            }
        }
    }

    fun addNoteElement() {
        _uiState.update { state ->
            val element = PageElement(
                id = nextLocalId(),
                entryId = state.entryId ?: 0,
                type = ElementType.NOTE,
                content = "",
                x = 0.5f,
                y = 0.5f,
                zIndex = nextZIndex(state.elements)
            )
            state.copy(elements = state.elements + element)
        }
    }

    fun addTextElement() {
        _uiState.update { state ->
            val element = PageElement(
                id = nextLocalId(),
                entryId = state.entryId ?: 0,
                type = ElementType.TEXT,
                content = "",
                x = 0.5f,
                y = 0.5f,
                zIndex = nextZIndex(state.elements)
            )
            state.copy(elements = state.elements + element)
        }
    }

    fun addStickerElement(glyph: String) {
        _uiState.update { state ->
            val element = PageElement(
                id = nextLocalId(),
                entryId = state.entryId ?: 0,
                type = ElementType.STICKER,
                content = glyph,
                x = 0.5f,
                y = 0.5f,
                zIndex = nextZIndex(state.elements)
            )
            state.copy(elements = state.elements + element)
        }
    }

    fun updateElementText(id: Long, text: String) {
        _uiState.update { state ->
            state.copy(elements = state.elements.map { if (it.id == id) it.copy(content = text) else it })
        }
    }

    fun updateElementColor(id: Long, colorHex: String?) {
        _uiState.update { state ->
            state.copy(elements = state.elements.map { if (it.id == id) it.copy(colorHex = colorHex) else it })
        }
    }

    fun updateElementShape(id: Long, shape: NoteShape) {
        _uiState.update { state ->
            state.copy(elements = state.elements.map { if (it.id == id) it.copy(shape = shape) else it })
        }
    }

    fun bringToFront(id: Long) {
        _uiState.update { state ->
            val nextZ = nextZIndex(state.elements)
            state.copy(elements = state.elements.map { if (it.id == id) it.copy(zIndex = nextZ) else it })
        }
    }

    fun transformElement(id: Long, normalizedPan: Offset, rotationDelta: Float, zoom: Float) {
        _uiState.update { state ->
            state.copy(
                elements = state.elements.map { element ->
                    if (element.id != id) return@map element
                    element.copy(
                        x = (element.x + normalizedPan.x).coerceIn(0f, 1f),
                        y = (element.y + normalizedPan.y).coerceIn(0f, 1f),
                        rotationDegrees = element.rotationDegrees + rotationDelta,
                        scale = (element.scale * zoom).coerceIn(0.3f, 3f)
                    )
                }
            )
        }
    }

    fun removeElement(id: Long) {
        val element = _uiState.value.elements.firstOrNull { it.id == id } ?: return
        if (element.type == ElementType.PHOTO) {
            viewModelScope.launch(Dispatchers.IO) { File(element.content).delete() }
        }
        _uiState.update { state -> state.copy(elements = state.elements.filterNot { it.id == id }) }
    }

    fun save() {
        val current = _uiState.value
        viewModelScope.launch {
            val primaryNote = current.elements
                .firstOrNull { it.type == ElementType.NOTE || it.type == ElementType.TEXT }
                ?.content.orEmpty()
            val primaryImagePath = current.elements.firstOrNull { it.type == ElementType.PHOTO }?.content
            val savedEntryId = journalRepository.saveEntry(
                JournalEntry(
                    id = current.entryId ?: 0,
                    mood = current.mood,
                    note = primaryNote,
                    createdAt = current.createdAt,
                    imagePath = primaryImagePath,
                    weatherCode = current.weatherCode,
                    tempC = current.tempC
                )
            )
            pageElementRepository.replaceAll(savedEntryId, current.elements)
            _uiState.update { it.copy(entryId = savedEntryId, isSaved = true) }
        }
    }
}
